GameClasses.elementTypeEnum = {WATER: 0, FIRE: 1, WOOD: 2, LIGHT: 3, DARK: 4}
GameClasses.slingTypeEnum = {BOUNCE: 0, PIERCE: 1, BOUNCE_2: 2, PIERCE_2: 3}
GameClasses.skillTypeEnum = {LASER_SINGLE_UP: 0, LASER_SINGLE_DOWN: 1, LASER_SINGLE_LEFT: 2, LASER_SINGLE_RIGHT: 3, LASER_DOUBLE_HORIZONTAL: 4, LASER_DOUBLE_VERTICAL: 5, LASER_CROSS_1: 6, LASER_CROSS_2: 7, LASER_TRACK: 8}
GameClasses.skillLevelEnum = {LASER_S: 0, LASER_M: 1, LASER_L: 2, LASER_EL: 3}
